apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-performance-probe-deployment
  labels:
    app: network-performance-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-performance-probe
  template:
    metadata:
      name: network-performance-probe
      labels:
        app: network-performance-probe
    spec:
      containers:
        - name: network-performance-probe
          image: kaiser1414/network-performance-probe:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
            - containerPort: 5001
          args: ['verbose', 'live', '--host', '127.0.0.1', '--port', '80', '--throughput', '--latency', '--packet-loss', '--prometheus', '5001']
      restartPolicy: Always
      