apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-probe
  labels:
      app: network-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-probe
  template:
    metadata:
      labels:
        app: network-probe
    spec:
      nodeName: netma-test-1
      containers:
        - name: network-probe
          image: kaiser1414/network-performance-probe:latest
#          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
            - containerPort: 5001
          command: ['python', 'network_probe.py']
          args: ['--verbose', '--host', '127.0.0.1', '--port', '80', '--throughput', '--latency', '--packet-loss', '--prometheus', '5001']
      restartPolicy: Always
      