apiVersion: v1
kind: Service
metadata:
  name: network-probe-service
spec:
  selector:
    app: network-probe
  ports:
    - name: http-5000
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: http-5001
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
